FROM node:20-alpine


WORKDIR /app

# We copy package.json first to leverage Docker layer caching
COPY package*.json ./

RUN npm install

# This line is not needed as the volume will mount the source code
# COPY . .

EXPOSE 5173
# The command is specified in docker-compose.dev.yml